services:
  nginx:
    container_name: note-nginx
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    env_file:
      - .env
