services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: "unless-stopped"
    env_file:
      - .env
    volumes:
      - ./client/src:/app/src

  nginx:
    image: nginx:1.26-alpine3.20
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
    ports:
      - 8082:80
