services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: "unless-stopped"
    volumes:
      - ./api/src:/app/src
      - ./api/logs:/app/logs
      - ./api/dist:/app/dist
    env_file:
      - .env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: "unless-stopped"
    depends_on:
      - api
    volumes:
      - ./client/src:/app/src

  nginx:
    image: nginx:1.26-alpine3.20
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - client
    ports:
      - 8082:80
