FROM node:18-alpine3.21

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN corepack enable && corepack prepare pnpm@10.8.0 --activate

RUN pnpm install --frozen-lockfile

COPY . .

CMD [ "pnpm", "run", "dev" ]
